# pull official base image
FROM node:16-alpine3.12 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY ./ ./

RUN npm install --silent
CMD ["npm", "run", "start"]
