version: '3.3'

services:
  mongodb:
    image: mongo:4.4.10
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    volumes:
      - "./data:/var/lib/mongodb"
    ports:
      - "27017:27017"

  api:
    build:
      dockerfile: Dockerfile.server
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://root:rootroot@mongodb:27017/pirates?authSource=admin

  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    depends_on:
      - api
    ports:
      - "80:80"
